/**
 * Generate worker/seed-assets.generated.ts — the travelkit skill tree, inlined as strings so
 * the Worker can push it into each per-user sandbox's /code via fetch (the sandbox file API).
 * Run before build/deploy: `pnpm gen:seed`.
 *
 * No credential is baked here: the per-user Simplifly token is injected at runtime into
 * /code/.simplifly.env (a dotenv file the skill reads) by worker/seed.ts (applyCredential). The
 * output is gitignored as a rebuilt artifact.
 */
import { createHash } from 'node:crypto'
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = process.cwd()

function walk(dir: string): string[] {
  const out: string[] = []
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) out.push(...walk(p))
    else out.push(p)
  }
  return out
}

const files: Record<string, string> = {}

// NOTE: no credential file is baked here. The per-user Simplifly token comes from the iframe
// handoff at runtime — worker/seed.ts writes /code/.simplifly.env (a dotenv file the travelkit-pro
// skill reads directly; it no longer relies on shell env vars). Keeps this artifact credential-free.

// The travelkit-pro skill tree (renamed from `travelkit`; the old tree is removed from each sandbox
// at re-seed via worker/seed.ts STALE_FILES).
const skillRoot = join(ROOT, '.claude', 'skills', 'travelkit-pro')
for (const abs of walk(skillRoot)) {
  const rel = '.claude/skills/travelkit-pro/' + abs.slice(skillRoot.length + 1).split('\\').join('/')
  files[rel] = readFileSync(abs, 'utf8')
}

// Content stamp over the seeded tree (sorted rel paths + bytes). When the skill changes, this
// changes — worker/task-do.ts compares it against each sandbox's recorded seed_version and
// re-pushes the files into already-provisioned VMs (no reprovision). Bump CREDENTIAL_SCHEMA below
// to also force a re-seed when the credential FORMAT changes (credentialsEnv) without skill edits.
const CREDENTIAL_SCHEMA = 'v2' // /code/.simplifly.env dotenv { SIMPLIFLY_BASE_URL, SIMPLIFLY_AUTH_TOKEN }
const hash = createHash('sha256').update(CREDENTIAL_SCHEMA + '\0')
for (const rel of Object.keys(files).sort()) hash.update(rel + '\0' + files[rel] + '\0')
const SEED_VERSION = hash.digest('hex').slice(0, 16)

const out =
  `// AUTO-GENERATED by scripts/gen-seed-assets.ts — do not edit. Gitignored rebuilt artifact\n` +
  `// (no secrets; the per-user Simplifly token is injected at runtime, not baked). The Worker\n` +
  `// writes these into each per-user sandbox's /code via fetch.\n` +
  `export const SEED_VERSION = ${JSON.stringify(SEED_VERSION)}\n` +
  `export const SEED_FILES: Record<string, string> = ${JSON.stringify(files, null, 2)}\n`

writeFileSync(join(ROOT, 'worker', 'seed-assets.generated.ts'), out)
console.log(`wrote worker/seed-assets.generated.ts — ${Object.keys(files).length} files, seed ${SEED_VERSION}`)
